# Netlify configuration for ArtVR Client
[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Headers for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"